### ISSUE TITLE
Can't compile with Clang 3.5.0 on ArchLinux x86_64

### ISSUE THREAD

**Issue by ghost** [airdcnano/airdcnano#10]
Compiling was fixed for GCC 4.9.1, but Clang 3.5.0 still complains. Here's the error:

```
In file included from client/FileReader.cpp:270:
/usr/include/setjmp.h:59:12: fatal error: conflicting types for '__sigsetjmp'
extern int __sigsetjmp (struct __jmp_buf_tag __env[1], int __savemask) __THROWNL;
           ^
/usr/include/pthread.h:745:12: note: previous declaration is here
extern int __sigsetjmp (struct __jmp_buf_tag *__env, int __savemask) __THROWNL;
           ^
1 error generated.
scons: *** [build/beta/client/FileReader.o] Error 1
```
